name: Add issues and PRs to a project
on: workflow_call

jobs:
  add-to-project:
    name: Add issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/workflowtests/projects/1
          github-token: ${{ github.token }}
